### ISSUE TITLE
setup genomic data in docker

### ISSUE THREAD

**Issue by lzj1769** [SchulzLab/EpigenomeAnalysisTutorial-2020#2]
It's better to set up the genomic data of RGT in docker, as python setupGenomicData.py --hg38 is not working for Mac

**Comment by skarunan** [comment]
@lzj1769 As far as I understand, it is not an issue of mac. The docker container is running a Debian 10 (buster) linux OS.

 The hg38 download finishes, but the script is getting killed. And to my understanding, the renaming of the dowloaded file is not happening. 

I'll add the file to EpigenomeAnalysisTutorial-2020/data/genome_hg38.fa

**Comment by lzj1769** [comment]
@skarunan sure, that will great! 👍 

I don't know why, but python setupGenomicData.py --hg38 is working perfectly for my ubuntu-desktop.
since both you and Ivan are using Mac, I thought it's an issue of mac.  :)

**Comment by skarunan** [comment]
Done.
