### ISSUE TITLE
libpng12.so.0 is missing

### ISSUE THREAD

**Issue by lzj1769** [SchulzLab/EpigenomeAnalysisTutorial-2020#3]
Step2.4 is still failing with the error you said earlier: error while loading shared libraries: libpng12.so.0

**Comment by lzj1769** [comment]
@skarunan 

here is the solution that I found for this issue:
```
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
dpkg -i /tmp/libpng12.deb
rm /tmp/libpng12.deb
```
it's working for me on my ubuntu-desktop

**Comment by skarunan** [comment]
Thanks. Also works in my docker container.

I'll commit the new docker image once I finish testing your part completely @lzj1769
