### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by lzj1769** [SchulzLab/EpigenomeAnalysisTutorial-2020#4]
error from step 2.4 in practical 1:

rgt-motifanalysis matching --organism=hg38 --output-location=./results/session1/hint_chr21/motifmatching --input-files ./results/session1/hint_chr21/footprints/hESC.bed ./results/session1/hint_chr21/footprints/Cardiac.bed
>> output location: ./results/session1/hint_chr21/motifmatching

>> genome: hg38
>> pseudocounts: 1.0
>> fpr threshold: 0.0001

>> loading input files..
>>> hESC, 2517 regions
>>> Cardiac, 7986 regions

>> loading motif databases..
>>> jaspar_vertebrates

Illegal instruction (core dumped)

**Comment by lzj1769** [comment]
It seems this is a MOODS-related issue, which has been reported in rgt-motifanalysis and MOODS:
https://github.com/CostaLab/reg-gen/issues/57
https://github.com/jhkorhonen/MOODS/issues/19
https://github.com/bioconda/bioconda-recipes/issues/9079

**Comment by lzj1769** [comment]
here is solution:
```
pip uninstall MOODS-python
conda install -c bioconda moods
```
@skarunan can you implement it and update the docker?

**Comment by skarunan** [comment]
This solution works in my docker container
