### ISSUE TITLE
Index file needs an update? ./data/nf_core_atacseq/Cardiac.mRp.clN.sorted.bam.bai

### ISSUE THREAD

**Issue by skarunan** [SchulzLab/EpigenomeAnalysisTutorial-2020#5]
I get the warning message in steps 2.3, 2.4 and 4.1:
The index file is older than the data file: ./data/nf_core_atacseq/Cardiac.mRp.clN.sorted.bam.bai

In 4.1 specially this warning is printed out 100s of time after the message generating signal for condition cardiac.

**Comment by lzj1769** [comment]
this is a warning message about bam file index and can be ignored.
I will add it to the docs.

**Comment by lzj1769** [comment]
@skarunan 

actually, we can try to generate new index files by:
```
samtools index ./EpigenomeAnalysisTutorial-2020/data/nf_core_atacseq/hESC.mRp.clN.sorted.bam
samtools index ./EpigenomeAnalysisTutorial-2020/data/nf_core_atacseq/Cardiac.mRp.clN.sorted.bam
```
can you do this? 
or I can do it and send the new index files to you.

**Comment by skarunan** [comment]
could you please send the new index files?

**Comment by lzj1769** [comment]
you can download them from here:
https://www.dropbox.com/sh/5aq3usob9pbo1rr/AADd3XNUbuCvyAZ01UIv3K5aa?dl=0

but looks like the new index files are exactly the same as the old ones, as they have the same hash code.
anyway, if the warning message still exists, I will add some comments regarding this.

**Comment by skarunan** [comment]
Thanks, it's fixed now!
