### ISSUE TITLE
Step-4: line plot generation taking too long

### ISSUE THREAD

**Issue by skarunan** [SchulzLab/EpigenomeAnalysisTutorial-2020#6]
I ran the command:

`rgt-hint differential --organism=hg38 --bc --nc 30 --mpbs-files=./results/session1/hint_chr21/motifmatching/hESC_mpbs.bed,./results/session1/hint_chr21/motifmatching/Cardiac_mpbs.bed --reads-files=./data/nf_core_atacseq/hESC.mRp.clN.sorted.bam,./data/nf_core_atacseq/Cardiac.mRp.clN.sorted.bam --conditions=hESC,Cardiac --output-location=./results/session1/hint_chr21/diff_footprints`

The script has been running for more than 15 mins now with a message "generating line plots for each motif"

@lzj1769 How many line plots are you trying to generate? 
I am wondering: Could we reduce the number of generated line plots in this step? We already have the lineplots for whole genome anyways, so the participants don't really have any use for these files. Please correct me if I'm wrong.

**Comment by skarunan** [comment]
` 2 cpus are detected and 30 of them will be used...`
This was the first line of output after Step-4 command. What does the 30 mean here?

**Comment by lzj1769** [comment]
> The script has been running for more than 15 mins now with a message "generating line plots for each motif"

yes, this step is quite computationally expensive and usually takes a few hours, depending on how many CPUs you are using.

>How many line plots are you trying to generate?

here, we will generate line plot for each motif, so total, more than 700 plots will be generated.

>I am wondering: Could we reduce the number of generated line plots in this step? We already have the lineplots for whole genome anyways, so the participants don't really have any use for these files. Please correct me if I'm wrong.

I think maybe we can try to use chromosome 22, which is smaller than 21.

>2 cpus are detected and 30 of them will be used...
>This was the first line of output after Step-4 command. What does the 30 mean here?

means rgt-hint will use 30 cpus for computation, which is a usual number for me when I run it on HPC. I guess most laptops don't have such many cpus, so I will suggest the participants to set this option accordingly.

**Comment by skarunan** [comment]
Thanks Li! 

> means rgt-hint will use 30 cpus for computation, which is a usual number for me when I run it on HPC. I guess most laptops don't have such many cpus, so I will suggest the participants to set this option accordingly.

Sure, you can ask them to set it. However, I think, if they have only 1 or 2 cpus to run them it will take even longer. The participants probably won't be able to complete this step at all. So is it really worth running it ?
Because in the next step they'll just be running an Rscript to plot the diff footprints of the whole genome from the previously stored results, isn't it?

**Comment by lzj1769** [comment]
> Sure, you can ask them to set it. However, I think, if they have only 1 or 2 cpus to run them it will take even longer. The participants probably won't be able to complete this step at all. So is it really worth running it ?

sure, maybe they don't need to wait until this step is completed, after 1-2 minutes when they run this command, we can start the next step. I will add some comments to indicate this.

> Because in the next step they'll just be running an Rscript to plot the diff footprints of the whole genome from the previously stored results, isn't it?

exactly

**Comment by skarunan** [comment]
> maybe they don't need to wait until this step is completed, after 1-2 minutes when they run this command, we can start the next step

If there is a way to restrict the number of motifs (maybe like 10 motifs or so), it would be good to do so. It will help the participants get an idea.

**Comment by lzj1769** [comment]
> If there is a way to restrict the number of motifs (maybe like 10 motifs or so), it would be good to do so. It will help the participants get an idea.

In theory, it is possible, rgt-hint differential command will read the motif matching results and perform the comparison. To reduce the number of motifs, we just need to grep some of them from the matching results, if we have a motif list.

however, this is not recommended for our analysis, because
i) the purpose of footprinting and motif analysis is to narrow down the candidate list which includes more than 700 motifs in an unbias way.
ii) the normalization will be broken if too few motifs are provided, the assumption behind differential footprinting is most of the motifs are supposed to be unchanged, so we can use them to normalize the sequencing depth.

**Comment by lzj1769** [comment]
@skarunan 

To reduce the running time of rgt-hint differential, one way will be using the option --no-lineplots to not generate the line plots, for example:
`rgt-hint differential --organism=hg38 --bc --nc 30 --mpbs-files=./results/session1/hint_chr21/motifmatching/hESC_mpbs.bed,./results/session1/hint_chr21/motifmatching/Cardiac_mpbs.bed --reads-files=./data/nf_core_atacseq/hESC.mRp.clN.sorted.bam,./data/nf_core_atacseq/Cardiac.mRp.clN.sorted.bam --conditions=hESC,Cardiac --output-location=./results/session1/hint_chr21/diff_footprints --no-lineplots`

after testing on my desktop by only using 2 cpus, now this step can be done in 2 minutes.
