### ISSUE TITLE
Cannot find ~/container-data for windows system

### ISSUE THREAD

**Issue by lzj1769** [SchulzLab/EpigenomeAnalysisTutorial-2020#7]
@skarunan 

I asked my colleague to test the tutorial using windows 10 pro, after running
`docker run -it -P --name epigenomics -v ~/container-data:/data sivarajank/epigenomics_tutorial:latest`
he couldn't find ~/container-data folder.

**Comment by skarunan** [comment]
Well, it should be in their home directory! 

I think, in windows10 it corresponds to `C:\Users\Username ` or  `C:\home\username`

**Comment by skarunan** [comment]
@lzj1769 I found something on the internet for a similar issue. Could you ask your colleague to try the accepted answer from here?

https://superuser.com/questions/1051520/docker-windows-container-how-to-mount-a-host-folder-as-data-volume-on-windows

**Comment by lzj1769** [comment]
sure, will do that.

it will be better if we can make this clear to these windows users in installation docs.

**Comment by skarunan** [comment]
@lzj1769 If the solution works, pls let me know. And, I can add an alternative command for windows user in the readthedocs

**Comment by skarunan** [comment]
added windows command
